--- #YAML:1.0
name:                Imager-SkinDetector
version:             0.01
abstract:            The great new Imager::SkinDetector!
license:             ~
author:              
    - Cosimo Streppone <cosimo@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Imager:                        0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
